- name: Regenerate apt-cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install default packages
  apt: name={{ item }} state=present
  with_items:
    - aptitude
    - bash
    - cpp
    - dos2unix
    - gcc
    - sqlite3
    - unzip
    - wget
    - ntp
    - supervisor

- name: Create UNIX regular users
  user: name={{ item }} password={{ default_unix_password }} shell=/bin/bash state=present
  with_items:  unix_users
  when: item != "root"
